kind: scene-fragment
schema_version: 1

entities:
- id: main-menu-global-lights
  name: global-lights
  tags:
  - lighting
  - global-light
  visible: true
  simulation_enabled: false
  collision_enabled: false
  components:
  - type: GlobalLight2D
    id: lightning
    color: '#B8D8FFFF'
    intensity: 0.0
  - type: GlobalLight2D
    id: beacon-red
    color: '#FF2A1EFF'
    intensity: 0.0
