[package]
name = "amigo-app"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
amigo-app-host-api.workspace = true
amigo-app-host-winit.workspace = true
amigo-assets.workspace = true
amigo-capabilities.workspace = true
amigo-core.workspace = true
amigo-file-watch-api.workspace = true
amigo-font.workspace = true
amigo-hot-reload.workspace = true
amigo-input-api.workspace = true
amigo-math.workspace = true
amigo-modding.workspace = true
amigo-devtools.workspace = true
amigo-editor-authoring.workspace = true
amigo-editor-ingame.workspace = true
amigo-render-api.workspace = true
amigo-render-wgpu.workspace = true
amigo-runtime.workspace = true
amigo-runtime-control.workspace = true
amigo-runtime-bundles.workspace = true
amigo-camera-optics-plugin.workspace = true
amigo-session.workspace = true
amigo-scene.workspace = true
amigo-scripting-api.workspace = true
amigo-state.workspace = true
amigo-window-api.workspace = true
serde_yaml.workspace = true
