[package]
name = "amigo-render-wgpu"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
amigo-2d-spatial.workspace = true
amigo-assets.workspace = true
amigo-font.workspace = true
amigo-core.workspace = true
amigo-fx.workspace = true
amigo-math.workspace = true
amigo-runtime.workspace = true
amigo-plugin-api.workspace = true
amigo-overlay-api.workspace = true
amigo-camera.workspace = true
amigo-render-api.workspace = true
amigo-material-api.workspace = true
amigo-ui-layout.workspace = true
amigo-window-api.workspace = true
image.workspace = true
wgpu.workspace = true
fontdue.workspace = true
