[package]
name = "amigo-render-wgpu"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
amigo-sprite-2d-plugin.workspace = true
amigo-2d-lighting-beacon.workspace = true
amigo-2d-layered-image.workspace = true
amigo-2d-lighting.workspace = true
amigo-2d-composition.workspace = true
amigo-2d-spatial.workspace = true
amigo-2d-post-fx.workspace = true
amigo-text-2d-plugin.workspace = true
amigo-vector-2d-plugin.workspace = true
amigo-2d-particles.workspace = true
amigo-2d-tilemap.workspace = true
amigo-3d-material.workspace = true
amigo-3d-mesh.workspace = true
amigo-3d-text.workspace = true
amigo-assets.workspace = true
amigo-font.workspace = true
amigo-core.workspace = true
amigo-fx.workspace = true
amigo-math.workspace = true
amigo-runtime.workspace = true
amigo-plugin-api.workspace = true
amigo-render-api.workspace = true
amigo-camera-optics-plugin.workspace = true
amigo-focus-depth-plugin.workspace = true
amigo-ui-layout.workspace = true
amigo-scene.workspace = true
amigo-window-api.workspace = true
image.workspace = true
wgpu.workspace = true
fontdue.workspace = true
