[package]
name = "amigo-scene"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
amigo-assets.workspace = true
amigo-2d-spatial.workspace = true
amigo-2d-post-fx.workspace = true
amigo-core.workspace = true
amigo-fx.workspace = true
amigo-math.workspace = true
amigo-plugin-api.workspace = true
amigo-runtime.workspace = true
amigo-session.workspace = true
amigo-scripting-api.workspace = true
amigo-camera-optics-plugin.workspace = true
serde.workspace = true
serde_yaml.workspace = true
