use amigo_scene::*;

pub fn vector_shape_2d_descriptor() -> ComponentTypeDescriptor {
    ComponentTypeDescriptor {
        kind: ComponentKind::VectorShape2D,
        type_name: "VectorShape2D",
        label: "Vector Shape 2D",
        domains: &[ComponentDomain::Render2D],
        owner_scopes: ENTITY_OWNER_SCOPES,
        default_yaml: None,
        metadata_traits: &[
            MetadataTraitKind::Renderable2D,
            MetadataTraitKind::RenderLayered2D,
            MetadataTraitKind::UsesTransform2D,
            MetadataTraitKind::Selectable,
            MetadataTraitKind::HasBounds2D,
            MetadataTraitKind::HasEditorControls,
            MetadataTraitKind::GenericEditable,
        ],
        asset_refs: &[],
        properties: &[
            EditorPropertyDescriptor {
                path: "render_layer",
                label: "Render Layer",
                value_kind: EditorPropertyValueKind::String,
                access: EditorPropertyAccess::Editable,
                editor: EditorPropertyEditorKind::Text,
                asset_domain: None,
                trait_kind: Some(MetadataTraitKind::RenderLayered2D),
                group: "render2d.order",
                patch_op: None,
                number_constraints: None,
                options: &[],
                visibility: EditorPropertyVisibility::Primary,
                order: 0,
                tags: &["Unsupported"],
                readonly_reason: Some("No live runtime binding yet"),
                binding_template: None,
            },
            EditorPropertyDescriptor {
                path: "kind",
                label: "Shape Kind",
                value_kind: EditorPropertyValueKind::Enum,
                access: EditorPropertyAccess::Editable,
                editor: EditorPropertyEditorKind::EnumSelect,
                asset_domain: None,
                trait_kind: Some(MetadataTraitKind::Renderable2D),
                group: "render2d.content",
                patch_op: None,
                number_constraints: None,
                options: &[],
                visibility: EditorPropertyVisibility::Primary,
                order: 0,
                tags: &["Unsupported"],
                readonly_reason: Some("No live runtime binding yet"),
                binding_template: None,
            },
            EditorPropertyDescriptor {
                path: "points",
                label: "Points",
                value_kind: EditorPropertyValueKind::String,
                access: EditorPropertyAccess::ReadOnly,
                editor: EditorPropertyEditorKind::ReadOnly,
                asset_domain: None,
                trait_kind: Some(MetadataTraitKind::Renderable2D),
                group: "render2d.content",
                patch_op: Some(EditorPatchOpKind::SetVectorPoints),
                number_constraints: None,
                options: &[],
                visibility: EditorPropertyVisibility::Primary,
                order: 0,
                tags: &["Unsupported"],
                readonly_reason: Some("No live runtime binding yet"),
                binding_template: None,
            },
            EditorPropertyDescriptor {
                path: "closed",
                label: "Closed",
                value_kind: EditorPropertyValueKind::Bool,
                access: EditorPropertyAccess::Editable,
                editor: EditorPropertyEditorKind::Checkbox,
                asset_domain: None,
                trait_kind: Some(MetadataTraitKind::Renderable2D),
                group: "render2d.content",
                patch_op: Some(EditorPatchOpKind::SetVectorPoints),
                number_constraints: None,
                options: &[],
                visibility: EditorPropertyVisibility::Primary,
                order: 0,
                tags: &["Unsupported"],
                readonly_reason: Some("No live runtime binding yet"),
                binding_template: None,
            },
            EditorPropertyDescriptor {
                path: "radius",
                label: "Radius",
                value_kind: EditorPropertyValueKind::Number,
                access: EditorPropertyAccess::Editable,
                editor: EditorPropertyEditorKind::Number,
                asset_domain: None,
                trait_kind: Some(MetadataTraitKind::HasBounds2D),
                group: "bounds2.radius",
                patch_op: None,
                number_constraints: None,
                options: &[],
                visibility: EditorPropertyVisibility::Primary,
                order: 0,
                tags: &["Unsupported"],
                readonly_reason: Some("No live runtime binding yet"),
                binding_template: None,
            },
            EditorPropertyDescriptor {
                path: "segments",
                label: "Segments",
                value_kind: EditorPropertyValueKind::Number,
                access: EditorPropertyAccess::Editable,
                editor: EditorPropertyEditorKind::Number,
                asset_domain: None,
                trait_kind: Some(MetadataTraitKind::Renderable2D),
                group: "render2d.content",
                patch_op: None,
                number_constraints: None,
                options: &[],
                visibility: EditorPropertyVisibility::Primary,
                order: 0,
                tags: &["Unsupported"],
                readonly_reason: Some("No live runtime binding yet"),
                binding_template: None,
            },
            EditorPropertyDescriptor {
                path: "fill_color",
                label: "Fill Color",
                value_kind: EditorPropertyValueKind::Color,
                access: EditorPropertyAccess::Editable,
                editor: EditorPropertyEditorKind::Color,
                asset_domain: None,
                trait_kind: Some(MetadataTraitKind::Renderable2D),
                group: "render2d.color",
                patch_op: None,
                number_constraints: None,
                options: &[],
                visibility: EditorPropertyVisibility::Primary,
                order: 0,
                tags: &["Unsupported"],
                readonly_reason: Some("No live runtime binding yet"),
                binding_template: None,
            },
            EditorPropertyDescriptor {
                path: "stroke_color",
                label: "Stroke Color",
                value_kind: EditorPropertyValueKind::Color,
                access: EditorPropertyAccess::Editable,
                editor: EditorPropertyEditorKind::Color,
                asset_domain: None,
                trait_kind: Some(MetadataTraitKind::Renderable2D),
                group: "render2d.color",
                patch_op: None,
                number_constraints: None,
                options: &[],
                visibility: EditorPropertyVisibility::Primary,
                order: 0,
                tags: &["Unsupported"],
                readonly_reason: Some("No live runtime binding yet"),
                binding_template: None,
            },
            EditorPropertyDescriptor {
                path: "stroke_width",
                label: "Stroke Width",
                value_kind: EditorPropertyValueKind::Number,
                access: EditorPropertyAccess::Editable,
                editor: EditorPropertyEditorKind::Number,
                asset_domain: None,
                trait_kind: Some(MetadataTraitKind::Renderable2D),
                group: "render2d.color",
                patch_op: None,
                number_constraints: None,
                options: &[],
                visibility: EditorPropertyVisibility::Primary,
                order: 0,
                tags: &["Readonly"],
                readonly_reason: Some("Asset picker is not exposed in ingame editor yet"),
                binding_template: None,
            },
            EditorPropertyDescriptor {
                path: "z_index",
                label: "Z Index",
                value_kind: EditorPropertyValueKind::Number,
                access: EditorPropertyAccess::Editable,
                editor: EditorPropertyEditorKind::Number,
                asset_domain: None,
                trait_kind: Some(MetadataTraitKind::Renderable2D),
                group: "render2d.order",
                patch_op: None,
                number_constraints: Some(EDITOR_NUMBER_ORDER),
                options: &[],
                visibility: EditorPropertyVisibility::Primary,
                order: 0,
                tags: &[],
                readonly_reason: None,
                binding_template: None,
            },
        ],
        transform_policy: TransformPolicy::UsesEntityTransform2,
        bounds_policy: BoundsPolicy::DerivedFromGeometry2D,
        editor_controls: &[
            EditorControlKind::Transform2D,
            EditorControlKind::VectorVertex2D,
        ],
        patch_ops: &[
            EditorPatchOpKind::SetTransform2,
            EditorPatchOpKind::SetVectorPoints,
        ],
    }
}

pub struct Vector2dComponentMetadataProvider;

impl ComponentMetadataProvider for Vector2dComponentMetadataProvider {
    fn provider_id(&self) -> &'static str {
        "amigo.gfx.vector-2d"
    }

    fn register_component_metadata(&self, registry: &mut ComponentRegistry) {
        registry.insert(vector_shape_2d_descriptor());
    }
}
