use amigo_scene::*;

pub fn camera_2d_descriptor() -> ComponentTypeDescriptor {
    ComponentTypeDescriptor {
        kind_id: "Camera2D",
        type_name: "Camera2D",
        label: "Camera 2D",
        domains: &[ComponentDomain::Camera],
        owner_scopes: ENTITY_OWNER_SCOPES,
        default_yaml: None,
        metadata_traits: &[
            MetadataTraitKind::Camera,
            MetadataTraitKind::RenderableViewportSource,
            MetadataTraitKind::UsesTransform2D,
            MetadataTraitKind::Selectable,
            MetadataTraitKind::HasAssetRefs,
            MetadataTraitKind::HasEditorControls,
            MetadataTraitKind::GenericEditable,
        ],
        asset_refs: &[
            ComponentAssetRefDescriptor {
                field_path: "lens.profile",
                domain: AssetDomain::Raw,
                required: false,
                trait_kind: MetadataTraitKind::HasAssetRefs,
                group: "assetRefs.camera",
            },
            ComponentAssetRefDescriptor {
                field_path: "film.profile",
                domain: AssetDomain::Raw,
                required: false,
                trait_kind: MetadataTraitKind::HasAssetRefs,
                group: "assetRefs.camera",
            },
            ComponentAssetRefDescriptor {
                field_path: "look.profile",
                domain: AssetDomain::Raw,
                required: false,
                trait_kind: MetadataTraitKind::HasAssetRefs,
                group: "assetRefs.camera",
            },
            ComponentAssetRefDescriptor {
                field_path: "lens_surface.rain_profile",
                domain: AssetDomain::Raw,
                required: false,
                trait_kind: MetadataTraitKind::HasAssetRefs,
                group: "assetRefs.camera",
            },
        ],
        properties: &[
            EditorPropertyDescriptor {
                path: "exposure.iso",
                label: "Exposure ISO",
                value_kind: EditorPropertyValueKind::Number,
                access: EditorPropertyAccess::Editable,
                editor: EditorPropertyEditorKind::Number,
                asset_domain: None,
                trait_kind: Some(MetadataTraitKind::RuntimeControllable),
                group: "camera.exposure",
                patch_op: None,
                number_constraints: Some(EditorNumberConstraints {
                    min: Some(25.0),
                    max: Some(12800.0),
                    step: Some(1.0),
                    clamp: true,
                    unit: Some("iso"),
                    display_scale: 1.0,
                }),
                options: &[],
                visibility: EditorPropertyVisibility::Primary,
                order: 0,
                tags: &[],
                readonly_reason: None,
                binding_template: Some(EditorRuntimeBindingTemplate::MockOnly),
            },
            EditorPropertyDescriptor {
                path: "exposure.shutter_speed",
                label: "Shutter Speed",
                value_kind: EditorPropertyValueKind::Number,
                access: EditorPropertyAccess::Editable,
                editor: EditorPropertyEditorKind::Number,
                asset_domain: None,
                trait_kind: Some(MetadataTraitKind::RuntimeControllable),
                group: "camera.exposure",
                patch_op: None,
                number_constraints: Some(EditorNumberConstraints {
                    min: Some(0.0001),
                    max: Some(2.0),
                    step: Some(0.0001),
                    clamp: true,
                    unit: Some("s"),
                    display_scale: 1.0,
                }),
                options: &[],
                visibility: EditorPropertyVisibility::Primary,
                order: 1,
                tags: &[],
                readonly_reason: None,
                binding_template: Some(EditorRuntimeBindingTemplate::MockOnly),
            },
            EditorPropertyDescriptor {
                path: "aperture.focus_distance_m",
                label: "Focus Distance",
                value_kind: EditorPropertyValueKind::Number,
                access: EditorPropertyAccess::Editable,
                editor: EditorPropertyEditorKind::Number,
                asset_domain: None,
                trait_kind: Some(MetadataTraitKind::RuntimeControllable),
                group: "camera.aperture",
                patch_op: None,
                number_constraints: Some(EditorNumberConstraints {
                    min: Some(0.2),
                    max: Some(1000.0),
                    step: Some(0.1),
                    clamp: true,
                    unit: Some("m"),
                    display_scale: 1.0,
                }),
                options: &[],
                visibility: EditorPropertyVisibility::Primary,
                order: 2,
                tags: &[],
                readonly_reason: None,
                binding_template: Some(EditorRuntimeBindingTemplate::MockOnly),
            },
            EditorPropertyDescriptor {
                path: "aperture.focus_depth",
                label: "Focus Depth Override",
                value_kind: EditorPropertyValueKind::Number,
                access: EditorPropertyAccess::Editable,
                editor: EditorPropertyEditorKind::Number,
                asset_domain: None,
                trait_kind: Some(MetadataTraitKind::RuntimeControllable),
                group: "camera.aperture",
                patch_op: None,
                number_constraints: Some(EditorNumberConstraints {
                    min: Some(0.0),
                    max: Some(1.0),
                    step: Some(0.01),
                    clamp: true,
                    unit: None,
                    display_scale: 1.0,
                }),
                options: &[],
                visibility: EditorPropertyVisibility::Debug,
                order: 3,
                tags: &[],
                readonly_reason: Some("Low-level debug focus override"),
                binding_template: Some(EditorRuntimeBindingTemplate::MockOnly),
            },
            EditorPropertyDescriptor {
                path: "look.contrast",
                label: "Contrast",
                value_kind: EditorPropertyValueKind::Number,
                access: EditorPropertyAccess::Editable,
                editor: EditorPropertyEditorKind::Number,
                asset_domain: None,
                trait_kind: Some(MetadataTraitKind::RuntimeControllable),
                group: "camera.look",
                patch_op: None,
                number_constraints: None,
                options: &[],
                visibility: EditorPropertyVisibility::Primary,
                order: 4,
                tags: &[],
                readonly_reason: None,
                binding_template: Some(EditorRuntimeBindingTemplate::MockOnly),
            },
            EditorPropertyDescriptor {
                path: "look.saturation",
                label: "Saturation",
                value_kind: EditorPropertyValueKind::Number,
                access: EditorPropertyAccess::Editable,
                editor: EditorPropertyEditorKind::Number,
                asset_domain: None,
                trait_kind: Some(MetadataTraitKind::RuntimeControllable),
                group: "camera.look",
                patch_op: None,
                number_constraints: None,
                options: &[],
                visibility: EditorPropertyVisibility::Primary,
                order: 5,
                tags: &[],
                readonly_reason: None,
                binding_template: Some(EditorRuntimeBindingTemplate::MockOnly),
            },
            EditorPropertyDescriptor {
                path: "lens.profile",
                label: "Lens Profile",
                value_kind: EditorPropertyValueKind::AssetRef,
                access: EditorPropertyAccess::Editable,
                editor: EditorPropertyEditorKind::AssetPicker,
                asset_domain: Some(AssetDomain::Raw),
                trait_kind: Some(MetadataTraitKind::HasAssetRefs),
                group: "assetRefs.camera",
                patch_op: None,
                number_constraints: None,
                options: &[],
                visibility: EditorPropertyVisibility::Advanced,
                order: 6,
                tags: &[],
                readonly_reason: None,
                binding_template: Some(EditorRuntimeBindingTemplate::MockOnly),
            },
            EditorPropertyDescriptor {
                path: "film.profile",
                label: "Film Profile",
                value_kind: EditorPropertyValueKind::AssetRef,
                access: EditorPropertyAccess::Editable,
                editor: EditorPropertyEditorKind::AssetPicker,
                asset_domain: Some(AssetDomain::Raw),
                trait_kind: Some(MetadataTraitKind::HasAssetRefs),
                group: "assetRefs.camera",
                patch_op: None,
                number_constraints: None,
                options: &[],
                visibility: EditorPropertyVisibility::Advanced,
                order: 7,
                tags: &[],
                readonly_reason: None,
                binding_template: Some(EditorRuntimeBindingTemplate::MockOnly),
            },
            EditorPropertyDescriptor {
                path: "look.profile",
                label: "Look Profile",
                value_kind: EditorPropertyValueKind::AssetRef,
                access: EditorPropertyAccess::Editable,
                editor: EditorPropertyEditorKind::AssetPicker,
                asset_domain: Some(AssetDomain::Raw),
                trait_kind: Some(MetadataTraitKind::HasAssetRefs),
                group: "assetRefs.camera",
                patch_op: None,
                number_constraints: None,
                options: &[],
                visibility: EditorPropertyVisibility::Advanced,
                order: 8,
                tags: &[],
                readonly_reason: None,
                binding_template: Some(EditorRuntimeBindingTemplate::MockOnly),
            },
            EditorPropertyDescriptor {
                path: "lens_surface.rain_profile",
                label: "Rain Profile",
                value_kind: EditorPropertyValueKind::AssetRef,
                access: EditorPropertyAccess::Editable,
                editor: EditorPropertyEditorKind::AssetPicker,
                asset_domain: Some(AssetDomain::Raw),
                trait_kind: Some(MetadataTraitKind::HasAssetRefs),
                group: "assetRefs.camera",
                patch_op: None,
                number_constraints: None,
                options: &[],
                visibility: EditorPropertyVisibility::Advanced,
                order: 9,
                tags: &[],
                readonly_reason: None,
                binding_template: Some(EditorRuntimeBindingTemplate::MockOnly),
            },
            EditorPropertyDescriptor {
                path: "quality",
                label: "Quality Profile",
                value_kind: EditorPropertyValueKind::String,
                access: EditorPropertyAccess::Editable,
                editor: EditorPropertyEditorKind::Text,
                asset_domain: None,
                trait_kind: Some(MetadataTraitKind::RuntimeControllable),
                group: "camera.runtime",
                patch_op: None,
                number_constraints: None,
                options: &[],
                visibility: EditorPropertyVisibility::Advanced,
                order: 10,
                tags: &[],
                readonly_reason: None,
                binding_template: Some(EditorRuntimeBindingTemplate::MockOnly),
            },
            EditorPropertyDescriptor {
                path: "debug.view",
                label: "Debug View",
                value_kind: EditorPropertyValueKind::String,
                access: EditorPropertyAccess::Editable,
                editor: EditorPropertyEditorKind::Text,
                asset_domain: None,
                trait_kind: Some(MetadataTraitKind::RuntimeControllable),
                group: "camera.runtime",
                patch_op: None,
                number_constraints: None,
                options: &[],
                visibility: EditorPropertyVisibility::Debug,
                order: 11,
                tags: &[],
                readonly_reason: None,
                binding_template: Some(EditorRuntimeBindingTemplate::MockOnly),
            },
            EditorPropertyDescriptor {
                path: "lens_surface.lens_rain.enabled",
                label: "Lens Rain Enabled",
                value_kind: EditorPropertyValueKind::Bool,
                access: EditorPropertyAccess::Editable,
                editor: EditorPropertyEditorKind::Checkbox,
                asset_domain: None,
                trait_kind: Some(MetadataTraitKind::RuntimeControllable),
                group: "camera.lens_surface",
                patch_op: None,
                number_constraints: None,
                options: &[],
                visibility: EditorPropertyVisibility::Primary,
                order: 12,
                tags: &[],
                readonly_reason: None,
                binding_template: Some(EditorRuntimeBindingTemplate::MockOnly),
            },
            EditorPropertyDescriptor {
                path: "lens_surface.lens_rain.spawn_rate",
                label: "Lens Rain Spawn Rate",
                value_kind: EditorPropertyValueKind::Number,
                access: EditorPropertyAccess::Editable,
                editor: EditorPropertyEditorKind::Number,
                asset_domain: None,
                trait_kind: Some(MetadataTraitKind::RuntimeControllable),
                group: "camera.lens_surface",
                patch_op: None,
                number_constraints: Some(EDITOR_NUMBER_PARTICLE_RATE),
                options: &[],
                visibility: EditorPropertyVisibility::Primary,
                order: 13,
                tags: &[],
                readonly_reason: None,
                binding_template: Some(EditorRuntimeBindingTemplate::MockOnly),
            },
            EditorPropertyDescriptor {
                path: "lens_surface.lens_rain.distortion",
                label: "Lens Rain Distortion",
                value_kind: EditorPropertyValueKind::Number,
                access: EditorPropertyAccess::Editable,
                editor: EditorPropertyEditorKind::Number,
                asset_domain: None,
                trait_kind: Some(MetadataTraitKind::RuntimeControllable),
                group: "camera.lens_surface",
                patch_op: None,
                number_constraints: None,
                options: &[],
                visibility: EditorPropertyVisibility::Primary,
                order: 8,
                tags: &[],
                readonly_reason: None,
                binding_template: Some(EditorRuntimeBindingTemplate::MockOnly),
            },
        ],
        transform_policy: TransformPolicy::UsesEntityTransform2,
        bounds_policy: BoundsPolicy::CameraViewport2D,
        editor_controls: &[EditorControlKind::Camera2D, EditorControlKind::Transform2D],
        patch_ops: &[
            EditorPatchOpKind::SetTransform2,
            EditorPatchOpKind::SetCamera2D,
        ],
    }
}

#[derive(Default)]
pub struct Camera2dComponentMetadataProvider;

impl ComponentMetadataProvider for Camera2dComponentMetadataProvider {
    fn provider_id(&self) -> &'static str {
        "amigo.camera.camera-core"
    }

    fn register_component_metadata(&self, registry: &mut ComponentRegistry) {
        registry
            .try_insert(camera_2d_descriptor())
            .expect("duplicate Camera2D component metadata");
    }
}
