id = "new-project"
name = "New Project"
version = "0.1.0"
description = "New Amigo 2D project."
authors = ["Amigo Engine Team"]
dependencies = ["core"]

[[scenes]]
id = "start"
label = "Start"
path = "scenes/start"
launcher_visible = true

[[scenes]]
id = "test"
label = "New Scene"
description = ""
path = "scenes/test"
launcher_visible = false
