[package]
name = "amigo-focus-depth-plugin"
version = "0.1.0"
edition = "2021"

[dependencies]
amigo-plugin-api = { path = "../../../crates/core/plugin-api" }
amigo-camera-core-plugin = { path = "../camera-core" }
amigo-assets.workspace = true
amigo-capabilities.workspace = true
amigo-core.workspace = true
amigo-math.workspace = true
amigo-runtime.workspace = true
amigo-scene.workspace = true
amigo-session.workspace = true
amigo-2d-composition.workspace = true
amigo-layered-image-2d-plugin.workspace = true
amigo-beacon-light-2d-plugin.workspace = true
amigo-2d-particles.workspace = true
amigo-2d-spatial.workspace = true
amigo-sprite-2d-plugin.workspace = true
amigo-text-2d-plugin.workspace = true
amigo-vector-2d-plugin.workspace = true
amigo-render-api.workspace = true
