id: fx
version: 0.1.0
exports:
  - ids.rhai
  - math.rhai
  - sequence.rhai
  - menu_state.rhai
  - camera_dof_controls.rhai
  - main_menu_intro.rhai
  - camera_presets.rhai
  - neon_alley.rhai
  - rain.rhai
requires:
  capabilities: []
