[package]
name = "amigo-devtools"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
amigo-editor-api.workspace = true
amigo-audio-output.workspace = true
amigo-2d-composition.workspace = true
amigo-layered-image-2d-plugin.workspace = true
amigo-2d-lighting.workspace = true
amigo-2d-particles.workspace = true
amigo-2d-post-fx.workspace = true
amigo-core.workspace = true
amigo-input-api.workspace = true
amigo-runtime.workspace = true
amigo-assets.workspace = true
amigo-camera-core-plugin.workspace = true
amigo-focus-depth-plugin.workspace = true
amigo-math.workspace = true
amigo-plugin-api.workspace = true
amigo-render-api.workspace = true
amigo-render-wgpu.workspace = true
amigo-runtime-control.workspace = true
amigo-scene.workspace = true
amigo-session.workspace = true
amigo-scripting-api.workspace = true
