[package]
name = "amigo-light-2d-plugin"
version = "0.1.0"
edition = "2021"

[dependencies]
amigo-plugin-api = { path = "../../../crates/core/plugin-api" }
amigo-assets.workspace = true
amigo-capabilities.workspace = true
amigo-camera-optics-plugin.workspace = true
amigo-core.workspace = true
amigo-devtools.workspace = true
amigo-layered-image-2d-plugin.workspace = true
amigo-math.workspace = true
amigo-render-api.workspace = true
amigo-runtime.workspace = true
amigo-scene.workspace = true
amigo-session.workspace = true
amigo-scripting-api.workspace = true
