pub(crate) struct RhaiRuntimeServices {
    pub scene: Option<Arc<SceneService>>,
    pub sprite_scene: Option<Arc<SpriteSceneService>>,
    pub vector_scene: Option<Arc<VectorSceneService>>,
    pub motion_scene: Option<Arc<Motion2dSceneService>>,
    pub particle_scene: Option<Arc<Particle2dSceneService>>,
    pub particle_preset_scene: Option<Arc<ParticlePreset2dService>>,
    pub physics_scene: Option<Arc<Physics2dSceneService>>,
    pub post_fx: Option<Arc<PostFx2dService>>,
    pub camera_service: Option<Arc<CameraService>>,
    pub focus_targets_2d: Option<Arc<CameraFocusTarget2dService>>,
    pub pool_scene: Option<Arc<EntityPoolSceneService>>,
    pub lifetime_scene: Option<Arc<LifetimeSceneService>>,
    pub state_service: Option<Arc<SceneStateService>>,
    pub session_service: Option<Arc<SessionStateService>>,
    pub timer_service: Option<Arc<SceneTimerService>>,
    pub ui_theme_service: Option<Arc<UiThemeService>>,
    pub asset_catalog: Option<Arc<AssetCatalog>>,
    pub input_state: Option<Arc<InputState>>,
    pub launch_selection: Option<Arc<LaunchSelection>>,
    pub mod_catalog: Option<Arc<ModCatalog>>,
    pub diagnostics: Option<Arc<RuntimeDiagnostics>>,
    pub command_queue: Option<Arc<ScriptCommandQueue>>,
    pub event_queue: Option<Arc<ScriptEventQueue>>,
    pub console_queue: Option<Arc<DevConsoleQueue>>,
    pub input_actions: Option<Arc<InputActionService>>,
    pub trace_service: Option<Arc<ScriptTraceService>>,
    pub inspect_requests: Option<Arc<amigo_editor_api::InspectRequestService>>,
    pub runtime_control: Option<Arc<amigo_runtime_control::RuntimeControlService>>,
    pub binding_namespaces: Vec<String>,
}

impl RhaiRuntimeServices {
    pub fn resolve(registry: &ServiceRegistry) -> Self {
        Self {
            scene: registry.resolve::<SceneService>(),
            sprite_scene: registry.resolve::<SpriteSceneService>(),
            vector_scene: registry.resolve::<VectorSceneService>(),
            motion_scene: registry.resolve::<Motion2dSceneService>(),
            particle_scene: registry.resolve::<Particle2dSceneService>(),
            particle_preset_scene: registry.resolve::<ParticlePreset2dService>(),
            physics_scene: registry.resolve::<Physics2dSceneService>(),
            post_fx: registry.resolve::<PostFx2dService>(),
            camera_service: registry.resolve::<CameraService>(),
            focus_targets_2d: registry.resolve::<CameraFocusTarget2dService>(),
            pool_scene: registry.resolve::<EntityPoolSceneService>(),
            lifetime_scene: registry.resolve::<LifetimeSceneService>(),
            state_service: registry.resolve::<SceneStateService>(),
            session_service: registry.resolve::<SessionStateService>(),
            timer_service: registry.resolve::<SceneTimerService>(),
            ui_theme_service: registry.resolve::<UiThemeService>(),
            asset_catalog: registry.resolve::<AssetCatalog>(),
            input_state: registry.resolve::<InputState>(),
            launch_selection: registry.resolve::<LaunchSelection>(),
            mod_catalog: registry.resolve::<ModCatalog>(),
            diagnostics: registry.resolve::<RuntimeDiagnostics>(),
            command_queue: registry.resolve::<ScriptCommandQueue>(),
            event_queue: registry.resolve::<ScriptEventQueue>(),
            console_queue: registry.resolve::<DevConsoleQueue>(),
            input_actions: registry.resolve::<InputActionService>(),
            trace_service: registry.resolve::<ScriptTraceService>(),
            inspect_requests: registry.resolve::<amigo_editor_api::InspectRequestService>(),
            runtime_control: registry.resolve::<amigo_runtime_control::RuntimeControlService>(),
            binding_namespaces: registry
                .resolve::<amigo_scripting_api::ScriptBindingProviderRegistry>()
                .map(|providers| providers.namespaces())
                .unwrap_or_else(crate::bindings::registration::default_domain_namespaces),
        }
    }
}

impl RhaiScriptRuntime {
    fn from_services(services: RhaiRuntimeServices) -> Self {
        Self::new_with_services_and_ui_theme_and_particle_presets_with_post_fx(
            services.scene,
            services.sprite_scene,
            services.vector_scene,
            services.motion_scene,
            services.particle_scene,
            services.particle_preset_scene,
            services.physics_scene,
            services.post_fx,
            services.camera_service,
            services.focus_targets_2d,
            services.pool_scene,
            services.lifetime_scene,
            services.state_service,
            services.session_service,
            services.timer_service,
            services.ui_theme_service,
            services.asset_catalog,
            services.input_state,
            services.launch_selection,
            services.mod_catalog,
            services.diagnostics,
            services.command_queue,
            services.event_queue,
            services.console_queue,
            services.input_actions,
            services.trace_service,
            services.inspect_requests,
            services.runtime_control,
            services.binding_namespaces,
        )
    }
}
