use amigo_scene::*;

pub fn text_2d_descriptor() -> ComponentTypeDescriptor {
    ComponentTypeDescriptor {
        kind_id: "Text2D",
        type_name: "Text2D",
        label: "Text 2D",
        domains: &[ComponentDomain::Render2D],
        owner_scopes: ENTITY_OWNER_SCOPES,
        default_yaml: None,
        metadata_traits: &[
            MetadataTraitKind::Renderable2D,
            MetadataTraitKind::RenderLayered2D,
            MetadataTraitKind::UsesTransform2D,
            MetadataTraitKind::Selectable,
            MetadataTraitKind::HasBounds2D,
            MetadataTraitKind::HasAssetRefs,
            MetadataTraitKind::HasEditorControls,
            MetadataTraitKind::GenericEditable,
        ],
        asset_refs: &[ComponentAssetRefDescriptor {
            field_path: "font",
            domain: AssetDomain::Font,
            required: true,
            trait_kind: MetadataTraitKind::HasAssetRefs,
            group: "assetRefs.primary",
        }],
        properties: &[
            EditorPropertyDescriptor {
                path: "render_layer",
                label: "Render Layer",
                value_kind: EditorPropertyValueKind::String,
                access: EditorPropertyAccess::Editable,
                editor: EditorPropertyEditorKind::Text,
                asset_domain: None,
                trait_kind: Some(MetadataTraitKind::RenderLayered2D),
                group: "render2d.order",
                patch_op: None,
                number_constraints: None,
                options: &[],
                visibility: EditorPropertyVisibility::Primary,
                order: 0,
                tags: &["Unsupported"],
                readonly_reason: Some("No live runtime binding yet"),
                binding_template: None,
            },
            EditorPropertyDescriptor {
                path: "content",
                label: "Content",
                value_kind: EditorPropertyValueKind::String,
                access: EditorPropertyAccess::Editable,
                editor: EditorPropertyEditorKind::Text,
                asset_domain: None,
                trait_kind: Some(MetadataTraitKind::Renderable2D),
                group: "render2d.content",
                patch_op: Some(EditorPatchOpKind::SetTextContent),
                number_constraints: None,
                options: &[],
                visibility: EditorPropertyVisibility::Primary,
                order: 0,
                tags: &["Unsupported"],
                readonly_reason: Some("No live runtime binding yet"),
                binding_template: None,
            },
            EditorPropertyDescriptor {
                path: "font",
                label: "Font",
                value_kind: EditorPropertyValueKind::AssetRef,
                access: EditorPropertyAccess::ReadOnly,
                editor: EditorPropertyEditorKind::ReadOnly,
                asset_domain: Some(AssetDomain::Font),
                trait_kind: Some(MetadataTraitKind::HasAssetRefs),
                group: "assetRefs.primary",
                patch_op: None,
                number_constraints: None,
                options: &[],
                visibility: EditorPropertyVisibility::Advanced,
                order: 0,
                tags: &["Unsupported"],
                readonly_reason: Some("No live runtime binding yet"),
                binding_template: None,
            },
            EditorPropertyDescriptor {
                path: "bounds",
                label: "Bounds",
                value_kind: EditorPropertyValueKind::Vec2,
                access: EditorPropertyAccess::Editable,
                editor: EditorPropertyEditorKind::Vec2,
                asset_domain: None,
                trait_kind: Some(MetadataTraitKind::HasBounds2D),
                group: "bounds2.size",
                patch_op: Some(EditorPatchOpKind::SetTextBounds),
                number_constraints: None,
                options: &[],
                visibility: EditorPropertyVisibility::Primary,
                order: 0,
                tags: &["Unsupported"],
                readonly_reason: Some("No live runtime binding yet"),
                binding_template: None,
            },
            EditorPropertyDescriptor {
                path: "style.color",
                label: "Text Color",
                value_kind: EditorPropertyValueKind::Color,
                access: EditorPropertyAccess::Editable,
                editor: EditorPropertyEditorKind::Color,
                asset_domain: None,
                trait_kind: Some(MetadataTraitKind::Renderable2D),
                group: "render2d.text.style",
                patch_op: None,
                number_constraints: None,
                options: &[],
                visibility: EditorPropertyVisibility::Primary,
                order: 0,
                tags: &["Unsupported"],
                readonly_reason: Some("No live runtime binding yet"),
                binding_template: None,
            },
            EditorPropertyDescriptor {
                path: "style.opacity",
                label: "Text Opacity",
                value_kind: EditorPropertyValueKind::Number,
                access: EditorPropertyAccess::Editable,
                editor: EditorPropertyEditorKind::Number,
                asset_domain: None,
                trait_kind: Some(MetadataTraitKind::Renderable2D),
                group: "render2d.text.style",
                patch_op: None,
                number_constraints: Some(EDITOR_NUMBER_OPACITY),
                options: &[],
                visibility: EditorPropertyVisibility::Primary,
                order: 0,
                tags: &["Unsupported"],
                readonly_reason: Some("No live runtime binding yet"),
                binding_template: None,
            },
            EditorPropertyDescriptor {
                path: "style.font_size",
                label: "Font Size",
                value_kind: EditorPropertyValueKind::Number,
                access: EditorPropertyAccess::Editable,
                editor: EditorPropertyEditorKind::Number,
                asset_domain: None,
                trait_kind: Some(MetadataTraitKind::Renderable2D),
                group: "render2d.text.style",
                patch_op: None,
                number_constraints: Some(EDITOR_NUMBER_PARTICLE_SIZE),
                options: &[],
                visibility: EditorPropertyVisibility::Primary,
                order: 0,
                tags: &["Unsupported"],
                readonly_reason: Some("No live runtime binding yet"),
                binding_template: None,
            },
            EditorPropertyDescriptor {
                path: "style.align",
                label: "Text Align",
                value_kind: EditorPropertyValueKind::Enum,
                access: EditorPropertyAccess::Editable,
                editor: EditorPropertyEditorKind::EnumSelect,
                asset_domain: None,
                trait_kind: Some(MetadataTraitKind::Renderable2D),
                group: "render2d.text.style",
                patch_op: None,
                number_constraints: None,
                options: &[
                    EditorPropertyOption {
                        id: "left",
                        label: "Left",
                    },
                    EditorPropertyOption {
                        id: "center",
                        label: "Center",
                    },
                    EditorPropertyOption {
                        id: "right",
                        label: "Right",
                    },
                ],
                visibility: EditorPropertyVisibility::Advanced,
                order: 0,
                tags: &["Unsupported"],
                readonly_reason: Some("No live runtime binding yet"),
                binding_template: None,
            },
            EditorPropertyDescriptor {
                path: "style.blend",
                label: "Text Blend",
                value_kind: EditorPropertyValueKind::Enum,
                access: EditorPropertyAccess::Editable,
                editor: EditorPropertyEditorKind::EnumSelect,
                asset_domain: None,
                trait_kind: Some(MetadataTraitKind::Renderable2D),
                group: "render2d.text.style",
                patch_op: None,
                number_constraints: None,
                options: &[
                    EditorPropertyOption {
                        id: "alpha",
                        label: "Alpha",
                    },
                    EditorPropertyOption {
                        id: "additive",
                        label: "Additive",
                    },
                    EditorPropertyOption {
                        id: "multiply",
                        label: "Multiply",
                    },
                    EditorPropertyOption {
                        id: "screen",
                        label: "Screen",
                    },
                ],
                visibility: EditorPropertyVisibility::Advanced,
                order: 0,
                tags: &["Unsupported"],
                readonly_reason: Some("No live runtime binding yet"),
                binding_template: None,
            },
            EditorPropertyDescriptor {
                path: "style.shadow.color",
                label: "Shadow Color",
                value_kind: EditorPropertyValueKind::Color,
                access: EditorPropertyAccess::Editable,
                editor: EditorPropertyEditorKind::Color,
                asset_domain: None,
                trait_kind: Some(MetadataTraitKind::Renderable2D),
                group: "render2d.text.shadow",
                patch_op: None,
                number_constraints: None,
                options: &[],
                visibility: EditorPropertyVisibility::Advanced,
                order: 0,
                tags: &["Unsupported"],
                readonly_reason: Some("No live runtime binding yet"),
                binding_template: None,
            },
            EditorPropertyDescriptor {
                path: "style.shadow.offset",
                label: "Shadow Offset",
                value_kind: EditorPropertyValueKind::Vec2,
                access: EditorPropertyAccess::Editable,
                editor: EditorPropertyEditorKind::Vec2,
                asset_domain: None,
                trait_kind: Some(MetadataTraitKind::Renderable2D),
                group: "render2d.text.shadow",
                patch_op: None,
                number_constraints: None,
                options: &[],
                visibility: EditorPropertyVisibility::Advanced,
                order: 0,
                tags: &["Unsupported"],
                readonly_reason: Some("No live runtime binding yet"),
                binding_template: None,
            },
            EditorPropertyDescriptor {
                path: "style.outline.color",
                label: "Outline Color",
                value_kind: EditorPropertyValueKind::Color,
                access: EditorPropertyAccess::Editable,
                editor: EditorPropertyEditorKind::Color,
                asset_domain: None,
                trait_kind: Some(MetadataTraitKind::Renderable2D),
                group: "render2d.text.outline",
                patch_op: None,
                number_constraints: None,
                options: &[],
                visibility: EditorPropertyVisibility::Advanced,
                order: 0,
                tags: &["Unsupported"],
                readonly_reason: Some("No live runtime binding yet"),
                binding_template: None,
            },
            EditorPropertyDescriptor {
                path: "style.outline.width",
                label: "Outline Width",
                value_kind: EditorPropertyValueKind::Number,
                access: EditorPropertyAccess::Editable,
                editor: EditorPropertyEditorKind::Number,
                asset_domain: None,
                trait_kind: Some(MetadataTraitKind::Renderable2D),
                group: "render2d.text.outline",
                patch_op: None,
                number_constraints: Some(EDITOR_NUMBER_PARTICLE_SIZE),
                options: &[],
                visibility: EditorPropertyVisibility::Advanced,
                order: 0,
                tags: &["Unsupported"],
                readonly_reason: Some("No live runtime binding yet"),
                binding_template: None,
            },
            EditorPropertyDescriptor {
                path: "style.glow.color",
                label: "Glow Color",
                value_kind: EditorPropertyValueKind::Color,
                access: EditorPropertyAccess::Editable,
                editor: EditorPropertyEditorKind::Color,
                asset_domain: None,
                trait_kind: Some(MetadataTraitKind::Renderable2D),
                group: "render2d.text.glow",
                patch_op: None,
                number_constraints: None,
                options: &[],
                visibility: EditorPropertyVisibility::Advanced,
                order: 0,
                tags: &["Unsupported"],
                readonly_reason: Some("No live runtime binding yet"),
                binding_template: None,
            },
            EditorPropertyDescriptor {
                path: "style.glow.radius",
                label: "Glow Radius",
                value_kind: EditorPropertyValueKind::Number,
                access: EditorPropertyAccess::Editable,
                editor: EditorPropertyEditorKind::Number,
                asset_domain: None,
                trait_kind: Some(MetadataTraitKind::Renderable2D),
                group: "render2d.text.glow",
                patch_op: None,
                number_constraints: Some(EDITOR_NUMBER_PARTICLE_SIZE),
                options: &[],
                visibility: EditorPropertyVisibility::Advanced,
                order: 0,
                tags: &["Unsupported"],
                readonly_reason: Some("No live runtime binding yet"),
                binding_template: None,
            },
            EditorPropertyDescriptor {
                path: "style.glow.intensity",
                label: "Glow Intensity",
                value_kind: EditorPropertyValueKind::Number,
                access: EditorPropertyAccess::Editable,
                editor: EditorPropertyEditorKind::Number,
                asset_domain: None,
                trait_kind: Some(MetadataTraitKind::Renderable2D),
                group: "render2d.text.glow",
                patch_op: None,
                number_constraints: Some(EDITOR_NUMBER_OPACITY),
                options: &[],
                visibility: EditorPropertyVisibility::Advanced,
                order: 0,
                tags: &["Unsupported"],
                readonly_reason: Some("No live runtime binding yet"),
                binding_template: None,
            },
        ],
        transform_policy: TransformPolicy::UsesEntityTransform2,
        bounds_policy: BoundsPolicy::ComponentBounds2D { field: "bounds" },
        editor_controls: &[
            EditorControlKind::Transform2D,
            EditorControlKind::TextBounds2D,
        ],
        patch_ops: &[
            EditorPatchOpKind::SetTransform2,
            EditorPatchOpKind::SetTextContent,
            EditorPatchOpKind::SetTextBounds,
        ],
    }
}

#[derive(Default)]
pub struct Text2dComponentMetadataProvider;

impl ComponentMetadataProvider for Text2dComponentMetadataProvider {
    fn provider_id(&self) -> &'static str {
        "amigo.gfx.text-2d"
    }

    fn register_component_metadata(&self, registry: &mut ComponentRegistry) {
        registry
            .try_insert(text_2d_descriptor())
            .expect("duplicate Text2D component metadata");
    }
}
