[package]
name = "amigo-tilemap-2d-plugin"
version = "0.1.0"
edition = "2021"

[dependencies]
amigo-plugin-api = { path = "../../../crates/core/plugin-api" }
amigo-2d-physics.workspace = true
amigo-assets.workspace = true
amigo-capabilities.workspace = true
amigo-core.workspace = true
amigo-editor-api.workspace = true
amigo-math.workspace = true
amigo-render-api.workspace = true
amigo-runtime.workspace = true
amigo-scene.workspace = true
amigo-session.workspace = true
serde.workspace = true
serde_yaml.workspace = true
