use std::{collections::BTreeMap, path::Path};

use amigo_assets::{
    AssetCatalog, AssetKey, AssetManifest, AssetSourceKind, PreparedAsset, PreparedAssetKind,
};
use amigo_render_npr::{
    BrushDefinition, BrushInstance, BrushMedium, BrushReference, NprBlendMode, NprGeometrySource,
    NprLayerColorSource, NprStyleLayer, NprStyleLayers,
};

use crate::state::MODELS;

const ASSET_PREFIX: &str = "npr-playground/models/";

#[derive(Debug, Clone, serde::Serialize)]
pub struct NprModelDescriptor {
    pub id: String,
    pub label: String,
    pub source: String,
    pub state: String,
    pub kind: String,
    pub error: Option<String>,
    pub thumbnail: Option<String>,
}

/// The existing AssetCatalog remains the sole owner of loading state.
pub fn model_descriptors(catalog: &AssetCatalog) -> Vec<NprModelDescriptor> {
    catalog
        .asset_sources()
        .into_iter()
        .filter_map(|source| catalog.asset_source_snapshot(&source.id))
        .flat_map(|source| {
            source.entries.into_iter().filter_map(|entry| {
                let id = entry.key.as_str().strip_prefix(ASSET_PREFIX)?.to_owned();
                let (state, error) = match entry.state {
                    amigo_assets::AssetBrowserEntryState::Unloaded => ("unloaded", None),
                    amigo_assets::AssetBrowserEntryState::Loading => ("loading", None),
                    amigo_assets::AssetBrowserEntryState::Ready => ("ready", None),
                    amigo_assets::AssetBrowserEntryState::Failed { message } => {
                        ("failed", Some(message))
                    }
                };
                Some(NprModelDescriptor {
                    label: id.clone(),
                    id,
                    source: entry.source_id.as_str().into(),
                    state: state.into(),
                    kind: "mesh-3d".into(),
                    error,
                    thumbnail: None,
                })
            })
        })
        .collect()
}

/// Fixed-pose geometry preview generated by the same NPR domain projection.
/// Only numeric triangles enter SVG; imported strings never become markup.
pub fn thumbnail(root: &Path, model: &str, path: Option<&Path>) -> Result<String, String> {
    let render = crate::NprPlaygroundRenderService::default();
    render.load_models(root)?;
    if let Some(path) = path {
        render.load_model(model, path)?;
    }
    let mut settings = crate::state::Settings::for_scene(false);
    if !settings.objects.contains_key(model) {
        let mut object = settings.objects[&settings.selected].clone();
        object.model = model.into();
        settings.objects.clear();
        settings.objects.insert(model.into(), object);
    }
    settings.selected = model.into();
    settings.paused = true;
    settings.sketch_paused = true;
    settings.camera_distance = 4.5;
    render.rebuild(&settings, [96, 96])?;
    let mut triangles = render
        .snapshot()
        .ok_or("missing thumbnail packet")?
        .packet
        .fills
        .clone();
    triangles.sort_by(|a, b| {
        b.depths
            .iter()
            .sum::<f32>()
            .total_cmp(&a.depths.iter().sum::<f32>())
    });
    use std::fmt::Write;
    let mut svg = String::from(
        "<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 96 96'><rect width='96' height='96' fill='#222936'/>",
    );
    for triangle in triangles {
        let [a, b, c] = triangle.positions;
        let color = triangle
            .color
            .to_array()
            .map(|c| (c.clamp(0., 1.) * 255.) as u8);
        write!(
            svg,
            "<path d='M{:.1},{:.1}L{:.1},{:.1} {:.1},{:.1}Z' fill='rgb({},{},{})'/>",
            a.x, a.y, b.x, b.y, c.x, c.y, color[0], color[1], color[2]
        )
        .map_err(|e| e.to_string())?;
    }
    svg.push_str("</svg>");
    Ok(format!(
        "data:image/svg+xml,{}",
        percent_encoding::utf8_percent_encode(&svg, percent_encoding::NON_ALPHANUMERIC)
    ))
}

/// A small, cached-on-demand rendering of a curated Look.  It consumes the
/// exact NPR packet used by the viewport, including its tessellated strokes;
/// the Svelte client never invents a visual substitute for a preset.
pub fn look_thumbnail(
    root: &Path,
    look_id: &str,
    brushes: &amigo_render_npr::BrushLibrary,
) -> Result<String, String> {
    let resolved = crate::playground::resolve_preview_look(root, look_id)?;
    let render = crate::NprPlaygroundRenderService::default();
    render.load_models(root)?;
    let mut settings = crate::state::Settings::for_scene(false);
    settings.global = resolved.style;
    settings.style_layers = resolved.layers;
    settings.brushes = brushes.clone();
    settings.paused = true;
    settings.sketch_paused = true;
    settings.camera_distance = 4.5;
    settings.validate()?;
    render.rebuild(&settings, [96, 96])?;
    packet_svg(
        render
            .snapshot()
            .ok_or("missing look preview packet")?
            .packet,
        &settings.style_layers,
    )
}

/// A renderer-generated Brush Lab sample.  Each medium receives its own
/// compatible NPR source; this prevents a wash or flat fill from being shown
/// as a misleading line-only swatch.
pub fn brush_thumbnail(root: &Path, brush: &BrushDefinition) -> Result<String, String> {
    brush.validate()?;
    let resolved = crate::playground::resolve_preview_look(root, "comic-ink")?;
    let source = match brush.medium {
        BrushMedium::Ink => NprGeometrySource::Silhouette,
        BrushMedium::Graphite => NprGeometrySource::FormLines,
        BrushMedium::Hatching => NprGeometrySource::ShadowHatch,
        BrushMedium::FlatFill => NprGeometrySource::FlatFill,
        BrushMedium::WatercolourWash => NprGeometrySource::Wash,
    };
    let mut settings = crate::state::Settings::for_scene(false);
    settings.global = resolved.style;
    settings.style_layers = resolved.layers;
    for layer in &mut settings.style_layers.layers {
        layer.enabled = layer.source == source;
        if layer.source == source {
            layer.brush = Some(BrushInstance {
                brush: BrushReference {
                    id: brush.id.clone(),
                    version: brush.version,
                },
                width: None,
                taper: None,
                softness: None,
                irregularity: None,
                dryness: None,
                seed: None,
            });
        }
    }
    let mut library = crate::documents::builtin_brush_library();
    library
        .brushes
        .entry(brush.id.clone())
        .or_default()
        .retain(|entry| entry.version != brush.version);
    library.add_version(brush.clone())?;
    settings.brushes = library;
    settings.paused = true;
    settings.sketch_paused = true;
    settings.camera_distance = 4.5;
    settings.validate()?;
    let render = crate::NprPlaygroundRenderService::default();
    render.load_models(root)?;
    render.rebuild(&settings, [96, 96])?;
    packet_svg(
        render
            .snapshot()
            .ok_or("missing brush preview packet")?
            .packet,
        &settings.style_layers,
    )
}

/// CPU preview compositor mirroring the authored layer order, colour, opacity,
/// blend and procedural coverage contract. It consumes the same expanded NPR
/// contributions as WGPU; SVG is used only to transport the result to the
/// companion without starting another GPU session.
fn packet_svg(
    packet: amigo_render_npr::NprRenderPacket,
    layers: &NprStyleLayers,
) -> Result<String, String> {
    use std::fmt::Write;
    let background = packet
        .background
        .to_array()
        .map(|c| (c.clamp(0., 1.) * 255.) as u8);
    let mut svg = format!(
        "<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 96 96'><rect width='96' height='96' fill='rgb({},{},{})'/>",
        background[0], background[1], background[2]
    );
    for layer in layers.layers.iter().filter(|layer| layer.enabled) {
        let blend = match layer.blend {
            NprBlendMode::Normal => "normal",
            NprBlendMode::Multiply => "multiply",
            NprBlendMode::Screen => "screen",
        };
        write!(svg, "<g style='mix-blend-mode:{blend};isolation:isolate'>")
            .map_err(|e| e.to_string())?;
        match layer.source {
            NprGeometrySource::FlatFill => {
                for triangle in packet
                    .fills
                    .iter()
                    .filter(|triangle| triangle.layer_id.as_deref() == Some(layer.id.as_str()))
                {
                    let color = preview_color(layer, triangle.color.to_array());
                    let coverage = triangle
                        .positions
                        .iter()
                        .zip(triangle.depths)
                        .map(|(position, depth)| preview_mask(layer, color, depth, *position))
                        .sum::<f32>()
                        / 3.0;
                    write_svg_triangle(
                        &mut svg,
                        triangle.positions,
                        color,
                        layer.opacity * coverage,
                    )?;
                }
            }
            NprGeometrySource::Wash => {
                for triangle in packet
                    .underpainting
                    .iter()
                    .filter(|triangle| triangle.layer_id.as_deref() == Some(layer.id.as_str()))
                {
                    let color = preview_color(layer, triangle.color.to_array());
                    let coverage = triangle
                        .positions
                        .iter()
                        .zip(triangle.depths)
                        .map(|(position, depth)| preview_mask(layer, color, depth, *position))
                        .sum::<f32>()
                        / 3.0;
                    write_svg_triangle(
                        &mut svg,
                        triangle.positions,
                        color,
                        layer.opacity
                            * triangle.coverage
                            * layer.paint.unwrap_or_default().wash
                            * coverage,
                    )?;
                }
            }
            NprGeometrySource::ShadowHatch
            | NprGeometrySource::FormLines
            | NprGeometrySource::Silhouette
            | NprGeometrySource::Creases
            | NprGeometrySource::Construction => {
                for stroke in packet
                    .strokes
                    .iter()
                    .filter(|stroke| stroke.layer_id.as_deref() == Some(layer.id.as_str()))
                {
                    let color = preview_color(layer, packet.stroke_color(stroke));
                    for indices in stroke.indices.chunks_exact(3) {
                        let (Some(a), Some(b), Some(c)) = (
                            stroke.vertices.get(indices[0] as usize),
                            stroke.vertices.get(indices[1] as usize),
                            stroke.vertices.get(indices[2] as usize),
                        ) else {
                            continue;
                        };
                        let coverage = [a, b, c]
                            .iter()
                            .map(|vertex| {
                                vertex.coverage
                                    * preview_mask(layer, color, vertex.depth, vertex.position)
                            })
                            .sum::<f32>()
                            / 3.0;
                        write_svg_triangle(
                            &mut svg,
                            [a.position, b.position, c.position],
                            color,
                            layer.opacity * coverage,
                        )?;
                    }
                }
            }
            NprGeometrySource::Paper => {}
        }
        svg.push_str("</g>");
    }
    svg.push_str("</svg>");
    Ok(format!(
        "data:image/svg+xml,{}",
        percent_encoding::utf8_percent_encode(&svg, percent_encoding::NON_ALPHANUMERIC)
    ))
}

fn preview_color(layer: &NprStyleLayer, fallback: [f32; 4]) -> [f32; 4] {
    match layer.color_source {
        NprLayerColorSource::Constant(color) => color.to_array(),
        NprLayerColorSource::StylePalette | NprLayerColorSource::ModelBaseColor => fallback,
    }
}

fn preview_mask(layer: &NprStyleLayer, color: [f32; 4], depth: f32, position: glam::Vec2) -> f32 {
    let tone = (color[0] * 0.2126 + color[1] * 0.7152 + color[2] * 0.0722).clamp(0.0, 1.0);
    let noise =
        (position.x.mul_add(12.9898, position.y * 78.233) + depth * 37.719).sin() * 0.5 + 0.5;
    layer
        .mask
        .evaluate(tone, depth.clamp(0.0, 1.0), [0.0, 0.0, 1.0], noise)
}

fn write_svg_triangle(
    svg: &mut String,
    [a, b, c]: [glam::Vec2; 3],
    color: [f32; 4],
    opacity: f32,
) -> Result<(), String> {
    use std::fmt::Write;
    let rgb = color.map(|channel| (channel.clamp(0.0, 1.0) * 255.0) as u8);
    write!(svg, "<path d='M{:.1},{:.1}L{:.1},{:.1} {:.1},{:.1}Z' fill='rgb({},{},{})' fill-opacity='{:.4}'/>", a.x, a.y, b.x, b.y, c.x, c.y, rgb[0], rgb[1], rgb[2], (color[3] * opacity).clamp(0.0, 1.0)).map_err(|error| error.to_string())
}

pub fn register_imported(
    catalog: &AssetCatalog,
    root: &Path,
    model: &crate::sources::NprImportedModel,
) {
    let source = AssetSourceKind::Mod(
        root.file_name()
            .unwrap_or_default()
            .to_string_lossy()
            .into_owned(),
    );
    let key = AssetKey::new(format!("{ASSET_PREFIX}{}", model.id));
    catalog.register_manifest(AssetManifest {
        key: key.clone(),
        source: source.clone(),
        tags: vec!["mesh-3d".into(), "npr-model".into()],
    });
    catalog.mark_loaded(amigo_assets::LoadedAsset {
        key: key.clone(),
        source: source.clone(),
        resolved_path: model.path.clone(),
        byte_len: model.byte_len,
    });
    catalog.mark_prepared(PreparedAsset {
        key,
        source,
        resolved_path: model.path.clone(),
        byte_len: model.byte_len,
        kind: PreparedAssetKind::Mesh3d,
        label: Some(model.id.clone()),
        format: Some("gltf".into()),
        metadata: BTreeMap::from([("npr.model".into(), model.id.clone())]),
    });
}

pub fn register_models(catalog: &AssetCatalog, mod_root: &Path) {
    for &model in MODELS {
        let key = AssetKey::new(format!("{ASSET_PREFIX}{model}"));
        let source = if matches!(model, "cube" | "wedge" | "cylinder" | "sphere") {
            AssetSourceKind::Engine
        } else {
            AssetSourceKind::Mod("npr-playground".into())
        };
        catalog.register_manifest(AssetManifest {
            key: key.clone(),
            source: source.clone(),
            tags: model_tags(model),
        });
        catalog.mark_prepared(PreparedAsset {
            key,
            source,
            resolved_path: mod_root.join("assets/models").join(model),
            byte_len: 0,
            kind: PreparedAssetKind::Mesh3d,
            label: Some(model.into()),
            format: Some("npr-prepared".into()),
            metadata: BTreeMap::from([("npr.model".into(), model.into())]),
        });
    }
}

fn model_tags(model: &str) -> Vec<String> {
    match model {
        "cube" | "wedge" => vec!["mesh-3d".into(), "hard-surface".into()],
        "cylinder" | "sphere" => vec!["mesh-3d".into(), "smooth".into()],
        "suzanne" | "avocado" => vec!["mesh-3d".into(), "organic".into()],
        _ => vec!["mesh-3d".into()],
    }
}

#[cfg(test)]
mod tests {
    use super::{brush_thumbnail, look_thumbnail};
    use std::path::PathBuf;

    fn mod_root() -> PathBuf {
        PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../../mods/npr-playground")
    }

    #[test]
    fn curated_looks_have_renderer_generated_preview_images() {
        for id in ["comic-ink", "pencil-study", "watercolour-wash"] {
            let preview = look_thumbnail(
                &mod_root(),
                id,
                &crate::documents::builtin_brush_library(),
            )
            .expect("curated look preview");
            assert!(preview.starts_with("data:image/svg+xml,"));
            assert!(
                preview.len() > 200,
                "{id} preview should contain NPR geometry"
            );
            let encoded = preview.strip_prefix("data:image/svg+xml,").unwrap();
            let svg = percent_encoding::percent_decode_str(encoded)
                .decode_utf8()
                .unwrap();
            assert!(
                svg.contains("mix-blend-mode:"),
                "{id} preview keeps layer blend"
            );
            assert!(
                svg.contains("fill-opacity="),
                "{id} preview keeps layer coverage"
            );
        }
    }

    #[test]
    fn every_builtin_brush_has_a_medium_appropriate_renderer_preview() {
        let library = crate::documents::builtin_brush_library();
        for versions in library.brushes.values() {
            for brush in versions {
                let preview = brush_thumbnail(&mod_root(), brush).expect("built-in brush preview");
                assert!(preview.starts_with("data:image/svg+xml,"));
                assert!(
                    preview.len() > 200,
                    "{} preview should contain NPR geometry",
                    brush.id
                );
            }
        }
    }
}
