[package]
name = "amigo-render-api"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
amigo-core.workspace = true
amigo-session.workspace = true
amigo-2d-spatial.workspace = true
amigo-camera.workspace = true
amigo-plugin-api = { path = "../../core/plugin-api" }
serde.workspace = true
