pub(crate) mod assets;
pub(crate) mod audio;
pub(crate) mod commands;
pub(crate) mod common;
pub(crate) mod debug;
pub(crate) mod entities;
pub(crate) mod input;
pub(crate) mod material3d;
pub(crate) mod mesh3d;
pub(crate) mod mod_api;
pub(crate) mod motion;
pub(crate) mod particles;
pub(crate) mod physics;
pub(crate) mod pools;
pub(crate) mod projectiles;
pub(crate) mod runtime;
pub(crate) mod scene;
pub(crate) mod session;
pub(crate) mod sprite2d;
pub(crate) mod state;
pub(crate) mod text2d;
pub(crate) mod text3d;
pub(crate) mod time;
pub(crate) mod timers;
pub(crate) mod ui;
pub(crate) mod vector2d;
pub(crate) mod world_root;

pub use assets::AssetsApi;
pub use audio::AudioApi;
pub use debug::DebugApi;
pub use entities::EntitiesApi;
pub use input::InputApi;
pub use material3d::Material3dApi;
pub use mesh3d::Mesh3dApi;
pub use mod_api::ModApi;
pub use motion::{MotionApi, MotionStateView};
pub use particles::ParticlesApi;
pub use physics::PhysicsApi;
pub use pools::PoolsApi;
pub use projectiles::ProjectilesApi;
pub use runtime::RuntimeApi;
pub use scene::SceneApi;
pub use session::SessionApi;
pub use sprite2d::Sprite2dApi;
pub use state::StateApi;
pub use text2d::Text2dApi;
pub use text3d::Text3dApi;
pub use time::{ScriptTimeState, TimeApi};
pub use timers::TimersApi;
pub use ui::UiApi;
pub use vector2d::Vector2dApi;
pub use world_root::WorldApi;

use crate::handles::{AssetRef, EntityRef};
use common::{string_to_bool, string_to_float, string_to_int};

pub fn register_world_api(engine: &mut rhai::Engine) {
    engine
        .register_type_with_name::<WorldApi>("World")
        .register_type_with_name::<SceneApi>("WorldScene")
        .register_type_with_name::<SessionApi>("WorldSession")
        .register_type_with_name::<EntitiesApi>("WorldEntities")
        .register_type_with_name::<InputApi>("WorldInput")
        .register_type_with_name::<PhysicsApi>("WorldPhysics")
        .register_type_with_name::<PoolsApi>("WorldPools")
        .register_type_with_name::<ProjectilesApi>("WorldProjectiles")
        .register_type_with_name::<TimeApi>("WorldTime")
        .register_type_with_name::<AssetsApi>("WorldAssets")
        .register_type_with_name::<AudioApi>("WorldAudio")
        .register_type_with_name::<ModApi>("WorldMod")
        .register_type_with_name::<MotionApi>("WorldMotion")
        .register_type_with_name::<ParticlesApi>("WorldParticles")
        .register_type_with_name::<MotionStateView>("MotionState")
        .register_type_with_name::<Sprite2dApi>("WorldSprite2d")
        .register_type_with_name::<StateApi>("WorldState")
        .register_type_with_name::<Vector2dApi>("WorldVector2d")
        .register_type_with_name::<Text2dApi>("WorldText2d")
        .register_type_with_name::<Mesh3dApi>("WorldMesh3d")
        .register_type_with_name::<Material3dApi>("WorldMaterial3d")
        .register_type_with_name::<Text3dApi>("WorldText3d")
        .register_type_with_name::<TimersApi>("WorldTimers")
        .register_type_with_name::<UiApi>("WorldUi")
        .register_type_with_name::<DebugApi>("WorldDebug")
        .register_type_with_name::<RuntimeApi>("WorldRuntime")
        .register_type_with_name::<EntityRef>("EntityRef")
        .register_type_with_name::<AssetRef>("AssetRef")
        .register_fn("to_float", string_to_float)
        .register_fn("to_int", string_to_int)
        .register_fn("to_bool", string_to_bool)
        .register_get("scene", WorldApi::scene)
        .register_get("entities", WorldApi::entities)
        .register_get("input", WorldApi::input)
        .register_get("physics", WorldApi::physics)
        .register_get("pools", WorldApi::pools)
        .register_get("projectiles", WorldApi::projectiles)
        .register_get("time", WorldApi::time)
        .register_get("assets", WorldApi::assets)
        .register_get("audio", WorldApi::audio)
        .register_get("mod", WorldApi::game_mod)
        .register_get("motion", WorldApi::motion)
        .register_get("particles", WorldApi::particles)
        .register_get("sprite2d", WorldApi::sprite2d)
        .register_get("state", WorldApi::state)
        .register_get("session", WorldApi::session)
        .register_get("vector", WorldApi::vector2d)
        .register_get("text2d", WorldApi::text2d)
        .register_get("mesh3d", WorldApi::mesh3d)
        .register_get("material3d", WorldApi::material3d)
        .register_get("text3d", WorldApi::text3d)
        .register_get("timers", WorldApi::timers)
        .register_get("ui", WorldApi::ui)
        .register_get("dev", WorldApi::dev)
        .register_get("runtime", WorldApi::runtime)
        .register_fn("current_id", SceneApi::current_id)
        .register_fn("available", SceneApi::available)
        .register_fn("has", SceneApi::has)
        .register_fn("select", SceneApi::select)
        .register_fn("reload", SceneApi::reload)
        .register_fn("activate_set", SceneApi::activate_set)
        .register_fn("named", EntitiesApi::named)
        .register_fn("create", EntitiesApi::create)
        .register_fn("exists", EntitiesApi::exists)
        .register_fn("count", EntitiesApi::count)
        .register_fn("names", EntitiesApi::names)
        .register_fn("distance", EntitiesApi::distance)
        .register_fn("set_position_2d", EntitiesApi::set_position_2d)
        .register_fn("position_2d", EntitiesApi::position_2d)
        .register_fn("set_rotation_2d", EntitiesApi::set_rotation_2d)
        .register_fn("hide", EntitiesApi::hide)
        .register_fn("show", EntitiesApi::show)
        .register_fn("enable", EntitiesApi::enable)
        .register_fn("disable", EntitiesApi::disable)
        .register_fn("set_collision_enabled", EntitiesApi::set_collision_enabled)
        .register_fn("is_visible", EntitiesApi::is_visible)
        .register_fn("is_enabled", EntitiesApi::is_enabled)
        .register_fn("collision_enabled", EntitiesApi::collision_enabled)
        .register_fn("hide_many", EntitiesApi::hide_many)
        .register_fn("by_tag", EntitiesApi::by_tag)
        .register_fn("by_group", EntitiesApi::by_group)
        .register_fn("active_by_tag", EntitiesApi::active_by_tag)
        .register_fn("has_tag", EntitiesApi::has_tag)
        .register_fn("has_group", EntitiesApi::has_group)
        .register_fn("property", EntitiesApi::property)
        .register_fn("property_int", EntitiesApi::property_int)
        .register_fn("property_float", EntitiesApi::property_float)
        .register_fn("property_bool", EntitiesApi::property_bool)
        .register_fn("property_string", EntitiesApi::property_string)
        .register_fn("set_property_int", EntitiesApi::set_property_int)
        .register_fn("set_property_float", EntitiesApi::set_property_float)
        .register_fn("set_property_bool", EntitiesApi::set_property_bool)
        .register_fn("set_property_string", EntitiesApi::set_property_string)
        .register_fn("down", InputApi::down)
        .register_fn("pressed", InputApi::pressed)
        .register_fn("any_down", InputApi::any_down)
        .register_fn("any_down", InputApi::any_down_array)
        .register_fn("any_pressed", InputApi::any_pressed)
        .register_fn("any_pressed", InputApi::any_pressed_array)
        .register_fn("axis", InputApi::axis)
        .register_fn("axis", InputApi::axis_array)
        .register_fn("keys", InputApi::keys)
        .register_fn("overlaps", PhysicsApi::overlaps)
        .register_fn("first_overlap", PhysicsApi::first_overlap)
        .register_fn("first_overlap_index", PhysicsApi::first_overlap_index)
        .register_fn("first_overlap_by_tag", PhysicsApi::first_overlap_by_tag)
        .register_fn("first_overlap_by_group", PhysicsApi::first_overlap_by_group)
        .register_fn(
            "first_overlap_by_selector",
            PhysicsApi::first_overlap_by_selector,
        )
        .register_fn("overlaps_by_tag", PhysicsApi::overlaps_by_tag)
        .register_fn("overlaps_by_group", PhysicsApi::overlaps_by_group)
        .register_fn("selector_candidates", PhysicsApi::selector_candidates)
        .register_fn("set_circle_radius", PhysicsApi::set_circle_radius)
        .register_fn("acquire", PoolsApi::acquire)
        .register_fn("release", PoolsApi::release)
        .register_fn("release_all", PoolsApi::release_all)
        .register_fn("members", PoolsApi::members)
        .register_fn("active_members", PoolsApi::active_members)
        .register_fn("active_count", PoolsApi::active_count)
        .register_fn("fire_from", ProjectilesApi::fire_from)
        .register_fn("release", ProjectilesApi::release)
        .register_fn("delta", TimeApi::delta)
        .register_fn("elapsed", TimeApi::elapsed)
        .register_fn("seconds", TimeApi::seconds)
        .register_fn("frame", TimeApi::frame)
        .register_fn("get", AssetsApi::get)
        .register_fn("has", AssetsApi::has)
        .register_fn("registered", AssetsApi::registered)
        .register_fn("by_mod", AssetsApi::by_mod)
        .register_fn("reload", AssetsApi::reload)
        .register_fn("pending", AssetsApi::pending)
        .register_fn("loaded", AssetsApi::loaded)
        .register_fn("prepared", AssetsApi::prepared)
        .register_fn("failed", AssetsApi::failed)
        .register_fn("play", AudioApi::play)
        .register_fn("cue", AudioApi::cue)
        .register_fn("preload", AudioApi::preload)
        .register_fn("play_asset", AudioApi::play_asset)
        .register_fn("start_realtime", AudioApi::start_realtime)
        .register_fn("stop", AudioApi::stop)
        .register_fn("set_param", AudioApi::set_param)
        .register_fn("set_volume", AudioApi::set_volume)
        .register_fn("current_id", ModApi::current_id)
        .register_fn("scenes", ModApi::scenes)
        .register_fn("has_scene", ModApi::has_scene)
        .register_fn("capabilities", ModApi::capabilities)
        .register_fn("loaded", ModApi::loaded)
        .register_fn("drive", MotionApi::drive)
        .register_fn("drive_freeflight", MotionApi::drive_freeflight)
        .register_fn("set_velocity", MotionApi::set_velocity)
        .register_fn("reset_freeflight", MotionApi::reset_freeflight)
        .register_fn("state", MotionApi::state)
        .register_fn("start", ParticlesApi::start)
        .register_fn("stop", ParticlesApi::stop)
        .register_fn("set_active", ParticlesApi::set_active)
        .register_fn("set_intensity", ParticlesApi::set_intensity)
        .register_fn("set_intensity", ParticlesApi::set_intensity_int)
        .register_fn("set_spawn_rate", ParticlesApi::set_spawn_rate)
        .register_fn("set_lifetime", ParticlesApi::set_lifetime)
        .register_fn("set_lifetime_jitter", ParticlesApi::set_lifetime_jitter)
        .register_fn("set_max_particles", ParticlesApi::set_max_particles)
        .register_fn("set_speed", ParticlesApi::set_speed)
        .register_fn("set_speed_jitter", ParticlesApi::set_speed_jitter)
        .register_fn("set_spread_degrees", ParticlesApi::set_spread_degrees)
        .register_fn(
            "set_local_direction_degrees",
            ParticlesApi::set_local_direction_degrees,
        )
        .register_fn(
            "set_inherit_parent_velocity",
            ParticlesApi::set_inherit_parent_velocity,
        )
        .register_fn("set_initial_size", ParticlesApi::set_initial_size)
        .register_fn("set_final_size", ParticlesApi::set_final_size)
        .register_fn("set_z_index", ParticlesApi::set_z_index)
        .register_fn("set_color_rgba", ParticlesApi::set_color_rgba)
        .register_fn("set_color_ramp4", ParticlesApi::set_color_ramp4)
        .register_fn("clear_color_ramp", ParticlesApi::clear_color_ramp)
        .register_fn("set_curve4", ParticlesApi::set_curve4)
        .register_fn("set_gravity", ParticlesApi::set_gravity)
        .register_fn("set_drag", ParticlesApi::set_drag)
        .register_fn("set_wind", ParticlesApi::set_wind)
        .register_fn("clear_forces", ParticlesApi::clear_forces)
        .register_fn("set_spawn_area_point", ParticlesApi::set_spawn_area_point)
        .register_fn("set_spawn_area_rect", ParticlesApi::set_spawn_area_rect)
        .register_fn("set_spawn_area_circle", ParticlesApi::set_spawn_area_circle)
        .register_fn("set_spawn_area_line", ParticlesApi::set_spawn_area_line)
        .register_fn("set_spawn_area_ring", ParticlesApi::set_spawn_area_ring)
        .register_fn("set_shape_circle", ParticlesApi::set_shape_circle)
        .register_fn("set_shape_line", ParticlesApi::set_shape_line)
        .register_fn("set_shape_quad", ParticlesApi::set_shape_quad)
        .register_fn("set_shape_mix", ParticlesApi::set_shape_mix)
        .register_fn("set_align", ParticlesApi::set_align)
        .register_fn("set_blend_mode", ParticlesApi::set_blend_mode)
        .register_fn("copy_config", ParticlesApi::copy_config)
        .register_fn("export_yaml", ParticlesApi::export_yaml)
        .register_fn("preset_ids", ParticlesApi::preset_ids)
        .register_fn("preset_label", ParticlesApi::preset_label)
        .register_fn("preset_category", ParticlesApi::preset_category)
        .register_fn("preset_tags", ParticlesApi::preset_tags)
        .register_fn("apply_preset", ParticlesApi::apply_preset)
        .register_fn("burst", ParticlesApi::burst)
        .register_fn("burst_at", ParticlesApi::burst_at)
        .register_fn("frame", Sprite2dApi::frame)
        .register_fn("set_frame", Sprite2dApi::set_frame)
        .register_fn("advance", Sprite2dApi::advance)
        .register_fn("queue", Sprite2dApi::queue)
        .register_fn("set_int", StateApi::set_int)
        .register_fn("set_float", StateApi::set_float)
        .register_fn("set_bool", StateApi::set_bool)
        .register_fn("set_string", StateApi::set_string)
        .register_fn("get_int", StateApi::get_int)
        .register_fn("get_float", StateApi::get_float)
        .register_fn("get_bool", StateApi::get_bool)
        .register_fn("get_string", StateApi::get_string)
        .register_fn("add_int", StateApi::add_int)
        .register_fn("add_float", StateApi::add_float)
        .register_fn("add_bool", StateApi::add_bool)
        .register_fn("add_string", StateApi::add_string)
        .register_fn("reset_scene", StateApi::reset_scene)
        .register_fn("set_int", SessionApi::set_int)
        .register_fn("set_float", SessionApi::set_float)
        .register_fn("set_bool", SessionApi::set_bool)
        .register_fn("set_string", SessionApi::set_string)
        .register_fn("get_int", SessionApi::get_int)
        .register_fn("get_float", SessionApi::get_float)
        .register_fn("get_bool", SessionApi::get_bool)
        .register_fn("get_string", SessionApi::get_string)
        .register_fn("add_int", SessionApi::add_int)
        .register_fn("add_float", SessionApi::add_float)
        .register_fn("add_bool", SessionApi::add_bool)
        .register_fn("add_string", SessionApi::add_string)
        .register_fn("set_polygon", Vector2dApi::set_polygon)
        .register_fn("set_polyline", Vector2dApi::set_polyline)
        .register_fn(
            "set_radial_jitter_polygon",
            Vector2dApi::set_radial_jitter_polygon,
        )
        .register_fn("queue", Text2dApi::queue)
        .register_fn("queue", Mesh3dApi::queue)
        .register_fn("bind", Material3dApi::bind)
        .register_fn("queue", Text3dApi::queue)
        .register_fn("start", TimersApi::start)
        .register_fn("ready", TimersApi::ready)
        .register_fn("active", TimersApi::active)
        .register_fn("after", TimersApi::after)
        .register_fn("tick", TimersApi::tick)
        .register_fn("advance", TimersApi::advance)
        .register_fn("reset_scene", TimersApi::reset_scene)
        .register_fn("set_text", UiApi::set_text)
        .register_fn("set_many", UiApi::set_many)
        .register_fn("set_value", UiApi::set_value)
        .register_fn("set_selected", UiApi::set_selected)
        .register_fn("set_options", UiApi::set_options)
        .register_fn("set_color", UiApi::set_color)
        .register_fn("set_background", UiApi::set_background)
        .register_fn("show", UiApi::show)
        .register_fn("hide", UiApi::hide)
        .register_fn("enable", UiApi::enable)
        .register_fn("disable", UiApi::disable)
        .register_fn("set_theme", UiApi::set_theme)
        .register_fn("theme", UiApi::theme)
        .register_fn("event", DebugApi::event)
        .register_fn("event", DebugApi::event_with_payload)
        .register_fn("command", DebugApi::command)
        .register_fn("log", DebugApi::log)
        .register_fn("warn", DebugApi::warn)
        .register_fn("write_text", DebugApi::write_text)
        .register_fn("refresh_diagnostics", DebugApi::refresh_diagnostics)
        .register_fn("window_backend", RuntimeApi::window_backend)
        .register_fn("input_backend", RuntimeApi::input_backend)
        .register_fn("render_backend", RuntimeApi::render_backend)
        .register_fn("script_backend", RuntimeApi::script_backend)
        .register_fn("capabilities", RuntimeApi::capabilities)
        .register_fn("plugins", RuntimeApi::plugins)
        .register_fn("services", RuntimeApi::services)
        .register_fn("dev_mode", RuntimeApi::dev_mode)
        .register_get("grounded", MotionStateView::grounded)
        .register_get("facing", MotionStateView::facing)
        .register_get("animation", MotionStateView::animation)
        .register_get("velocity_x", MotionStateView::velocity_x)
        .register_get("velocity_y", MotionStateView::velocity_y)
        .register_get("velocity_x_int", MotionStateView::velocity_x_int)
        .register_get("velocity_y_int", MotionStateView::velocity_y_int)
        .register_get("angle_radians", MotionStateView::angle_radians)
        .register_fn("name", EntityRef::name)
        .register_fn("exists", EntityRef::exists)
        .register_fn("rotate_2d", EntityRef::rotate_2d)
        .register_fn("rotate_3d", EntityRef::rotate_3d)
        .register_fn("set_position_2d", EntityRef::set_position_2d)
        .register_fn("hide", EntityRef::hide)
        .register_fn("show", EntityRef::show)
        .register_fn("enable", EntityRef::enable)
        .register_fn("disable", EntityRef::disable)
        .register_fn("set_collision_enabled", EntityRef::set_collision_enabled)
        .register_fn("is_visible", EntityRef::is_visible)
        .register_fn("is_enabled", EntityRef::is_enabled)
        .register_fn("collision_enabled", EntityRef::collision_enabled)
        .register_fn("has_tag", EntityRef::has_tag)
        .register_fn("has_group", EntityRef::has_group)
        .register_fn("property", EntityRef::property)
        .register_fn("property_int", EntityRef::property_int)
        .register_fn("property_float", EntityRef::property_float)
        .register_fn("property_bool", EntityRef::property_bool)
        .register_fn("property_string", EntityRef::property_string)
        .register_fn("key", AssetRef::key)
        .register_fn("exists", AssetRef::exists)
        .register_fn("state", AssetRef::state)
        .register_fn("source", AssetRef::source)
        .register_fn("path", AssetRef::path)
        .register_fn("kind", AssetRef::kind)
        .register_fn("label", AssetRef::label)
        .register_fn("format", AssetRef::format)
        .register_fn("tags", AssetRef::tags)
        .register_fn("reason", AssetRef::reason)
        .register_fn("reload", AssetRef::reload);
}
