pub(crate) fn default_domain_namespaces() -> Vec<String> {
    [
        "assets",
        "audio",
        "camera",
        "physics",
        "physics3d",
        "postfx",
        "pools",
        "projectiles",
        "mod",
        "motion",
        "particles",
        "sprite2d",
        "layered_image2d",
        "beacon2d",
        "light2d",
        "render2d",
        "state",
        "vector2d",
        "text2d",
        "mesh3d",
        "material3d",
        "text3d",
        "ui",
    ]
    .into_iter()
    .map(str::to_owned)
    .collect()
}

pub(crate) fn register_all(engine: &mut rhai::Engine, provider_namespaces: &[String]) {
    super::common::register_api(engine);
    super::world_root::register_api(engine);
    super::scene::register_api(engine);
    super::session::register_api(engine);
    super::entities::register_api(engine);
    super::input::register_api(engine);
    super::actions::register_api(engine);
    super::arcade::register_api(engine);
    super::random::register_api(engine);
    super::time::register_api(engine);
    super::timers::register_api(engine);
    super::trace::register_api(engine);
    super::debug::register_api(engine);
    super::runtime::register_api(engine);
    super::handle_refs::register_api(engine);
    super::installers::install_declared(engine, provider_namespaces);
}
