[package]
name = "amigo-editor-authoring"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
amigo-core.workspace = true
amigo-runtime.workspace = true
amigo-modding.workspace = true
amigo-session.workspace = true
amigo-scene.workspace = true
amigo-editor-api.workspace = true
serde.workspace = true
serde_yaml.workspace = true
