impl RhaiScriptRuntime {
    pub fn new(
        scene: Option<Arc<SceneService>>,
        sprite_scene: Option<Arc<SpriteSceneService>>,
        asset_catalog: Option<Arc<AssetCatalog>>,
        input_state: Option<Arc<InputState>>,
        launch_selection: Option<Arc<LaunchSelection>>,
        mod_catalog: Option<Arc<ModCatalog>>,
        diagnostics: Option<Arc<RuntimeDiagnostics>>,
        command_queue: Option<Arc<ScriptCommandQueue>>,
        event_queue: Option<Arc<ScriptEventQueue>>,
        console_queue: Option<Arc<DevConsoleQueue>>,
    ) -> Self {
        Self::new_with_motion(
            scene,
            sprite_scene,
            None,
            None,
            asset_catalog,
            input_state,
            launch_selection,
            mod_catalog,
            diagnostics,
            command_queue,
            event_queue,
            console_queue,
        )
    }

    pub fn new_with_motion(
        scene: Option<Arc<SceneService>>,
        sprite_scene: Option<Arc<SpriteSceneService>>,
        motion_scene: Option<Arc<Motion2dSceneService>>,
        physics_scene: Option<Arc<Physics2dSceneService>>,
        asset_catalog: Option<Arc<AssetCatalog>>,
        input_state: Option<Arc<InputState>>,
        launch_selection: Option<Arc<LaunchSelection>>,
        mod_catalog: Option<Arc<ModCatalog>>,
        diagnostics: Option<Arc<RuntimeDiagnostics>>,
        command_queue: Option<Arc<ScriptCommandQueue>>,
        event_queue: Option<Arc<ScriptEventQueue>>,
        console_queue: Option<Arc<DevConsoleQueue>>,
    ) -> Self {
        Self::new_with_motion_and_vector(
            scene,
            sprite_scene,
            None,
            motion_scene,
            physics_scene,
            asset_catalog,
            input_state,
            launch_selection,
            mod_catalog,
            diagnostics,
            command_queue,
            event_queue,
            console_queue,
        )
    }

    #[allow(clippy::too_many_arguments)]
    pub fn new_with_motion_and_vector(
        scene: Option<Arc<SceneService>>,
        sprite_scene: Option<Arc<SpriteSceneService>>,
        vector_scene: Option<Arc<VectorSceneService>>,
        motion_scene: Option<Arc<Motion2dSceneService>>,
        physics_scene: Option<Arc<Physics2dSceneService>>,
        asset_catalog: Option<Arc<AssetCatalog>>,
        input_state: Option<Arc<InputState>>,
        launch_selection: Option<Arc<LaunchSelection>>,
        mod_catalog: Option<Arc<ModCatalog>>,
        diagnostics: Option<Arc<RuntimeDiagnostics>>,
        command_queue: Option<Arc<ScriptCommandQueue>>,
        event_queue: Option<Arc<ScriptEventQueue>>,
        console_queue: Option<Arc<DevConsoleQueue>>,
    ) -> Self {
        Self::new_with_services(
            scene,
            sprite_scene,
            vector_scene,
            motion_scene,
            None,
            physics_scene,
            None,
            None,
            None,
            None,
            None,
            asset_catalog,
            input_state,
            launch_selection,
            mod_catalog,
            diagnostics,
            command_queue,
            event_queue,
            console_queue,
        )
    }

    #[allow(clippy::too_many_arguments)]
    fn new_with_services(
        scene: Option<Arc<SceneService>>,
        sprite_scene: Option<Arc<SpriteSceneService>>,
        vector_scene: Option<Arc<VectorSceneService>>,
        motion_scene: Option<Arc<Motion2dSceneService>>,
        particle_scene: Option<Arc<Particle2dSceneService>>,
        physics_scene: Option<Arc<Physics2dSceneService>>,
        pool_scene: Option<Arc<EntityPoolSceneService>>,
        lifetime_scene: Option<Arc<LifetimeSceneService>>,
        state_service: Option<Arc<SceneStateService>>,
        session_service: Option<Arc<SessionStateService>>,
        timer_service: Option<Arc<SceneTimerService>>,
        asset_catalog: Option<Arc<AssetCatalog>>,
        input_state: Option<Arc<InputState>>,
        launch_selection: Option<Arc<LaunchSelection>>,
        mod_catalog: Option<Arc<ModCatalog>>,
        diagnostics: Option<Arc<RuntimeDiagnostics>>,
        command_queue: Option<Arc<ScriptCommandQueue>>,
        event_queue: Option<Arc<ScriptEventQueue>>,
        console_queue: Option<Arc<DevConsoleQueue>>,
    ) -> Self {
        Self::new_with_services_and_ui_theme(
            scene,
            sprite_scene,
            vector_scene,
            motion_scene,
            particle_scene,
            physics_scene,
            pool_scene,
            lifetime_scene,
            state_service,
            session_service,
            timer_service,
            None,
            asset_catalog,
            input_state,
            launch_selection,
            mod_catalog,
            diagnostics,
            command_queue,
            event_queue,
            console_queue,
        )
    }

    #[allow(clippy::too_many_arguments)]
    fn new_with_services_and_ui_theme(
        scene: Option<Arc<SceneService>>,
        sprite_scene: Option<Arc<SpriteSceneService>>,
        vector_scene: Option<Arc<VectorSceneService>>,
        motion_scene: Option<Arc<Motion2dSceneService>>,
        particle_scene: Option<Arc<Particle2dSceneService>>,
        physics_scene: Option<Arc<Physics2dSceneService>>,
        pool_scene: Option<Arc<EntityPoolSceneService>>,
        lifetime_scene: Option<Arc<LifetimeSceneService>>,
        state_service: Option<Arc<SceneStateService>>,
        session_service: Option<Arc<SessionStateService>>,
        timer_service: Option<Arc<SceneTimerService>>,
        ui_theme_service: Option<Arc<UiThemeService>>,
        asset_catalog: Option<Arc<AssetCatalog>>,
        input_state: Option<Arc<InputState>>,
        launch_selection: Option<Arc<LaunchSelection>>,
        mod_catalog: Option<Arc<ModCatalog>>,
        diagnostics: Option<Arc<RuntimeDiagnostics>>,
        command_queue: Option<Arc<ScriptCommandQueue>>,
        event_queue: Option<Arc<ScriptEventQueue>>,
        console_queue: Option<Arc<DevConsoleQueue>>,
    ) -> Self {
        Self::new_with_services_and_ui_theme_and_particle_presets(
            scene,
            sprite_scene,
            vector_scene,
            motion_scene,
            particle_scene,
            None,
            physics_scene,
            pool_scene,
            lifetime_scene,
            state_service,
            session_service,
            timer_service,
            ui_theme_service,
            asset_catalog,
            input_state,
            launch_selection,
            mod_catalog,
            diagnostics,
            command_queue,
            event_queue,
            console_queue,
            None,
            None,
        )
    }

    #[allow(clippy::too_many_arguments)]
    fn new_with_services_and_ui_theme_and_particle_presets(
        scene: Option<Arc<SceneService>>,
        sprite_scene: Option<Arc<SpriteSceneService>>,
        vector_scene: Option<Arc<VectorSceneService>>,
        motion_scene: Option<Arc<Motion2dSceneService>>,
        particle_scene: Option<Arc<Particle2dSceneService>>,
        particle_preset_scene: Option<Arc<ParticlePreset2dService>>,
        physics_scene: Option<Arc<Physics2dSceneService>>,
        pool_scene: Option<Arc<EntityPoolSceneService>>,
        lifetime_scene: Option<Arc<LifetimeSceneService>>,
        state_service: Option<Arc<SceneStateService>>,
        session_service: Option<Arc<SessionStateService>>,
        timer_service: Option<Arc<SceneTimerService>>,
        ui_theme_service: Option<Arc<UiThemeService>>,
        asset_catalog: Option<Arc<AssetCatalog>>,
        input_state: Option<Arc<InputState>>,
        launch_selection: Option<Arc<LaunchSelection>>,
        mod_catalog: Option<Arc<ModCatalog>>,
        diagnostics: Option<Arc<RuntimeDiagnostics>>,
        command_queue: Option<Arc<ScriptCommandQueue>>,
        event_queue: Option<Arc<ScriptEventQueue>>,
        console_queue: Option<Arc<DevConsoleQueue>>,
        input_actions: Option<Arc<InputActionService>>,
        trace_service: Option<Arc<ScriptTraceService>>,
    ) -> Self {
        let time_state = Arc::new(ScriptTimeState::default());
        let state_service = state_service.unwrap_or_else(|| Arc::new(SceneStateService::default()));
        let session_service =
            session_service.unwrap_or_else(|| Arc::new(SessionStateService::default()));
        let timer_service = timer_service.unwrap_or_else(|| Arc::new(SceneTimerService::default()));
        let world = WorldApi::new(
            scene.clone(),
            sprite_scene.clone(),
            vector_scene.clone(),
            motion_scene.clone(),
            particle_scene.clone(),
            particle_preset_scene.clone(),
            physics_scene.clone(),
            pool_scene.clone(),
            lifetime_scene.clone(),
            Some(state_service.clone()),
            Some(session_service.clone()),
            Some(timer_service.clone()),
            ui_theme_service,
            asset_catalog.clone(),
            input_state.clone(),
            input_actions.clone(),
            time_state.clone(),
            launch_selection.clone(),
            mod_catalog.clone(),
            diagnostics.clone(),
            command_queue.clone(),
            event_queue.clone(),
            console_queue.clone(),
            trace_service,
        );
        let source_context = Arc::new(Mutex::new(None));
        Self {
            engine: build_engine(world.clone(), source_context.clone()),
            scripts: Mutex::new(BTreeMap::new()),
            time_state,
            timer_service,
            source_context,
            world,
        }
    }

}
