[package]
name = "amigo-2d-composition"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
amigo-capabilities.workspace = true
amigo-2d-spatial.workspace = true
amigo-core.workspace = true
amigo-render-api.workspace = true
amigo-runtime.workspace = true
amigo-scene.workspace = true
amigo-session.workspace = true
amigo-scripting-api.workspace = true
