[package]
name = "amigo-symbol-explorer"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
default-run = "amigo-symbol-explorer"

[dependencies]
anyhow = "1"
regex = "1"
serde.workspace = true
serde_json = "1"
serde_yaml.workspace = true
