use amigo_scene::*;

pub fn layered_image_2d_descriptor() -> ComponentTypeDescriptor {
    ComponentTypeDescriptor {
        kind_id: "LayeredImage2D",
        type_name: "LayeredImage2D",
        label: "Layered Image 2D",
        domains: &[ComponentDomain::Render2D],
        owner_scopes: ENTITY_OWNER_SCOPES,
        default_yaml: Some(
            "type: LayeredImage2D\nrender_layer: background.city\nasset: \"\"\nsize: { x: 1280.0, y: 720.0 }\nbase_opacity: 1.0\nviewport_fit: fixed\nz_index: 0.0\nlayer_overrides: []\n",
        ),
        metadata_traits: &[
            MetadataTraitKind::Renderable2D,
            MetadataTraitKind::RenderLayered2D,
            MetadataTraitKind::UsesTransform2D,
            MetadataTraitKind::Selectable,
            MetadataTraitKind::HasBounds2D,
            MetadataTraitKind::HasAssetRefs,
            MetadataTraitKind::HasEditorControls,
            MetadataTraitKind::GenericEditable,
            MetadataTraitKind::RuntimeControllable,
        ],
        asset_refs: &[ComponentAssetRefDescriptor {
            field_path: "asset",
            domain: AssetDomain::LayeredImage,
            required: true,
            trait_kind: MetadataTraitKind::HasAssetRefs,
            group: "assetRefs.primary",
        }],
        properties: &[
            EditorPropertyDescriptor {
                path: "asset",
                label: "Layered Image Asset",
                value_kind: EditorPropertyValueKind::AssetRef,
                access: EditorPropertyAccess::Editable,
                editor: EditorPropertyEditorKind::AssetPicker,
                asset_domain: Some(AssetDomain::LayeredImage),
                trait_kind: Some(MetadataTraitKind::HasAssetRefs),
                group: "assetRefs.primary",
                patch_op: None,
                number_constraints: None,
                options: &[],
                visibility: EditorPropertyVisibility::Primary,
                order: 0,
                tags: &[],
                readonly_reason: None,
                binding_template: None,
            },
            EditorPropertyDescriptor {
                path: "size",
                label: "Size",
                value_kind: EditorPropertyValueKind::Vec2,
                access: EditorPropertyAccess::Editable,
                editor: EditorPropertyEditorKind::Vec2,
                asset_domain: None,
                trait_kind: Some(MetadataTraitKind::HasBounds2D),
                group: "bounds2.size",
                patch_op: None,
                number_constraints: None,
                options: &[],
                visibility: EditorPropertyVisibility::Primary,
                order: 0,
                tags: &[],
                readonly_reason: None,
                binding_template: None,
            },
            EditorPropertyDescriptor {
                path: "render_layer",
                label: "Render Layer",
                value_kind: EditorPropertyValueKind::String,
                access: EditorPropertyAccess::ReadOnly,
                editor: EditorPropertyEditorKind::ReadOnly,
                asset_domain: None,
                trait_kind: Some(MetadataTraitKind::RenderLayered2D),
                group: "render2d.order",
                patch_op: None,
                number_constraints: None,
                options: &[],
                visibility: EditorPropertyVisibility::Advanced,
                order: 0,
                tags: &["Readonly"],
                readonly_reason: Some("Viewport fit is authoring/debug only"),
                binding_template: None,
            },
            EditorPropertyDescriptor {
                path: "z_index",
                label: "Z Index",
                value_kind: EditorPropertyValueKind::Number,
                access: EditorPropertyAccess::Editable,
                editor: EditorPropertyEditorKind::Number,
                asset_domain: None,
                trait_kind: Some(MetadataTraitKind::Renderable2D),
                group: "render2d.order",
                patch_op: None,
                number_constraints: None,
                options: &[],
                visibility: EditorPropertyVisibility::Primary,
                order: 0,
                tags: &[],
                readonly_reason: None,
                binding_template: None,
            },
            EditorPropertyDescriptor {
                path: "viewport_fit",
                label: "Viewport Fit",
                value_kind: EditorPropertyValueKind::String,
                access: EditorPropertyAccess::Editable,
                editor: EditorPropertyEditorKind::Text,
                asset_domain: None,
                trait_kind: Some(MetadataTraitKind::Renderable2D),
                group: "render2d.viewport",
                patch_op: None,
                number_constraints: None,
                options: &[],
                visibility: EditorPropertyVisibility::Primary,
                order: 0,
                tags: &[],
                readonly_reason: None,
                binding_template: None,
            },
            EditorPropertyDescriptor {
                path: "base_opacity",
                label: "Base Opacity",
                value_kind: EditorPropertyValueKind::Number,
                access: EditorPropertyAccess::Editable,
                editor: EditorPropertyEditorKind::Number,
                asset_domain: None,
                trait_kind: Some(MetadataTraitKind::RuntimeControllable),
                group: "render2d.layers",
                patch_op: None,
                number_constraints: Some(EDITOR_NUMBER_OPACITY),
                options: &[],
                visibility: EditorPropertyVisibility::Primary,
                order: 0,
                tags: &["Live"],
                readonly_reason: None,
                binding_template: Some(EditorRuntimeBindingTemplate::LayeredImageBaseOpacity),
            },
            EditorPropertyDescriptor {
                path: "layer_overrides",
                label: "Image Parts Source",
                value_kind: EditorPropertyValueKind::String,
                access: EditorPropertyAccess::ReadOnly,
                editor: EditorPropertyEditorKind::ReadOnly,
                asset_domain: None,
                trait_kind: Some(MetadataTraitKind::GenericEditable),
                group: "render2d.layers",
                patch_op: None,
                number_constraints: None,
                options: &[],
                visibility: EditorPropertyVisibility::Debug,
                order: 0,
                tags: &["Readonly"],
                readonly_reason: Some("Image Parts are exposed as semantic controls"),
                binding_template: None,
            },
        ],
        transform_policy: TransformPolicy::UsesEntityTransform2,
        bounds_policy: BoundsPolicy::ComponentBounds2D { field: "size" },
        editor_controls: &[EditorControlKind::Transform2D, EditorControlKind::Rect2D],
        patch_ops: &[EditorPatchOpKind::SetTransform2],
    }
}

#[derive(Default)]
pub struct LayeredImage2dComponentMetadataProvider;

impl ComponentMetadataProvider for LayeredImage2dComponentMetadataProvider {
    fn provider_id(&self) -> &'static str {
        "amigo.gfx.layered-image-2d"
    }

    fn register_component_metadata(&self, registry: &mut ComponentRegistry) {
        registry
            .try_insert(layered_image_2d_descriptor())
            .expect("duplicate LayeredImage2D component metadata");
    }
}
